-- Wayfare D1 schema v1.
-- Apply with: npx wrangler d1 migrations apply wayfare --remote
--
-- Conventions:
--   * ids are lowercase UUID strings (trip/item ids are generated by the client)
--   * *_at columns ending in "_ms" style (created_at, updated_at, deleted_at,
--     expires_at, last_*) are INTEGER milliseconds since epoch
--   * start_at / end_at on items are ISO-8601 UTC strings without fractional
--     seconds ("2026-10-01T14:30:00Z"), which sort correctly as text
--   * deletes of trips / items / memberships are soft (deleted_at set) so
--     /v1/sync can hand tombstones to other devices

CREATE TABLE users (
  id                  TEXT PRIMARY KEY,
  apple_sub           TEXT NOT NULL UNIQUE,
  display_name        TEXT NOT NULL DEFAULT '',
  email               TEXT,
  -- Sign in with Apple refresh token, kept only so DELETE /v1/me can revoke it.
  apple_refresh_token TEXT,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL
);

-- Only the SHA-256 hash (hex) of each session token is stored.
CREATE TABLE sessions (
  token_hash   TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   INTEGER NOT NULL,
  last_used_at INTEGER NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- One row per iPhone (keyed by its APNs token).
CREATE TABLE devices (
  apns_token            TEXT PRIMARY KEY,
  user_id               TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  environment           TEXT NOT NULL CHECK (environment IN ('sandbox', 'production')),
  time_zone             TEXT NOT NULL,
  briefing_enabled      INTEGER NOT NULL DEFAULT 1,
  briefing_hour         INTEGER NOT NULL DEFAULT 7 CHECK (briefing_hour BETWEEN 0 AND 23),
  collab_alerts_enabled INTEGER NOT NULL DEFAULT 1,
  -- Local date (device time zone) of the last briefing sent, so a repeated
  -- cron run or a DST fall-back hour never sends the same briefing twice.
  last_briefing_date    TEXT,
  updated_at            INTEGER NOT NULL
);
CREATE INDEX idx_devices_user ON devices(user_id);
CREATE INDEX idx_devices_briefing ON devices(briefing_enabled);

-- owner_id deliberately has no foreign key: when an owner deletes their
-- account the trip is kept as a content-free tombstone so collaborators'
-- devices learn to drop it.
CREATE TABLE trips (
  id          TEXT PRIMARY KEY,
  owner_id    TEXT NOT NULL,
  title       TEXT NOT NULL,
  destination TEXT NOT NULL DEFAULT '',
  start_date  TEXT NOT NULL,
  end_date    TEXT NOT NULL,
  time_zone   TEXT NOT NULL,
  cover_emoji TEXT NOT NULL DEFAULT '',
  color_hex   TEXT NOT NULL DEFAULT '#2F6FEB',
  notes       TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER
);
CREATE INDEX idx_trips_updated ON trips(updated_at);
CREATE INDEX idx_trips_owner ON trips(owner_id);

-- user_id has no foreign key for the same reason: a member who deletes their
-- account leaves a tombstone row behind so other members' lists update.
CREATE TABLE trip_members (
  trip_id    TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL,
  role       TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  PRIMARY KEY (trip_id, user_id)
);
CREATE INDEX idx_members_user ON trip_members(user_id, deleted_at);
CREATE INDEX idx_members_trip_updated ON trip_members(trip_id, updated_at);

CREATE TABLE items (
  id                TEXT PRIMARY KEY,
  trip_id           TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  kind              TEXT NOT NULL CHECK (kind IN ('flight', 'lodging', 'activity', 'food', 'transport', 'note')),
  title             TEXT NOT NULL,
  start_at          TEXT NOT NULL,
  end_at            TEXT,
  start_time_zone   TEXT NOT NULL,
  end_time_zone     TEXT,
  all_day           INTEGER NOT NULL DEFAULT 0,
  location_name     TEXT NOT NULL DEFAULT '',
  address           TEXT NOT NULL DEFAULT '',
  latitude          REAL,
  longitude         REAL,
  confirmation_code TEXT NOT NULL DEFAULT '',
  details           TEXT NOT NULL DEFAULT '{}',  -- JSON object of string -> string
  notes             TEXT NOT NULL DEFAULT '',
  reminder_minutes  INTEGER,
  sort_index        INTEGER NOT NULL DEFAULT 0,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL,
  updated_by        TEXT NOT NULL,
  deleted_at        INTEGER
);
CREATE INDEX idx_items_trip_updated ON items(trip_id, updated_at);
CREATE INDEX idx_items_trip_start ON items(trip_id, start_at);

CREATE TABLE invites (
  code       TEXT PRIMARY KEY,
  trip_id    TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  role       TEXT NOT NULL CHECK (role IN ('editor', 'viewer')),
  created_by TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL
);
CREATE INDEX idx_invites_trip ON invites(trip_id);
CREATE INDEX idx_invites_expires ON invites(expires_at);

-- Collaborator-push coalescing: last push time per (trip, recipient).
CREATE TABLE push_log (
  trip_id      TEXT NOT NULL,
  user_id      TEXT NOT NULL,
  last_sent_at INTEGER NOT NULL,
  PRIMARY KEY (trip_id, user_id)
);

-- AI import rate limit: count per user per UTC day ("YYYY-MM-DD").
CREATE TABLE import_usage (
  user_id TEXT NOT NULL,
  day     TEXT NOT NULL,
  count   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, day)
);
